name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: python:3.10.14
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pypoetry
            .venv
          key: poetry-lint-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            poetry-lint-

      - name: Install Poetry
        run: pip install poetry==1.8.3

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true
          poetry config --list

      - name: Install dependencies
        run: poetry install --with lint

      - name: Run ruff check
        run: poetry run ruff check

  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.10.14
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pypoetry
            .venv
          key: poetry-test-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            poetry-test-

      - name: Install Poetry
        run: pip install poetry==1.8.3

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true
          poetry config --list

      - name: Install dependencies
        run: poetry install --with test

      - name: Run pytest
        run: poetry run pytest
